steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
    waitFor:
      - Build
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
    waitFor:
      - Build
      - Push
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
    waitFor:
      - Build
      - Push
      - Prepare deploy
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
    waitFor:
      - Build
      - Push
      - Prepare deploy
      - Save configs
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
timeout: 2000s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DOCKERFILE_DIR: ''
  _K8S_ANNOTATIONS: gcb-trigger-id=c364fcb0-2ba8-4fa5-90e3-f8fce1e406e6
  _OUTPUT_BUCKET_PATH: bodha-qa_cloudbuild/deploy
  _IMAGE_NAME: gcr.io/bodha-qa/github.com/bodhaai/turk-assessment
  _K8S_NAMESPACE: default
  _K8S_YAML_PATH: deployment.yaml
  _GKE_LOCATION: us-central1-c
  _DOCKERFILE_NAME: Dockerfile
  _GKE_CLUSTER: bodha-qa-v1-cluster
  _K8S_APP_NAME: bodha-turk
  _K8S_LABELS: ''
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
